# === PROD / ORACLE ===
spring.datasource.url=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl
spring.datasource.username=RM555189
spring.datasource.password=040506
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# (opcionais para depuração)
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
