# === DEV / H2 ===
spring.datasource.url=jdbc:h2:mem:gameapi;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# se preferir arquivo em disco: jdbc:h2:file:./data/bankdb
spring.datasource.username=teste
spring.datasource.password=1234
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
