spring.profiles.active=prod
spring.application.name=gameapi

# Swagger (comum aos perfis)
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
