# === PROD TEMPORÁRIO COM H2 (sobe fácil) ===
spring.datasource.url=jdbc:h2:mem:gameapi
spring.datasource.username=teste
spring.datasource.password=1234
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# se você quiser usar flyway depois, beleza:
spring.flyway.enabled=false

server.port=8080

# Swagger liberado
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# JWT (igual ao dev por enquanto)
jwt.secret=dW1hX2NoYXZlX3NlY3JldGFfYmVtX2dyYW5kZV9hcXVpX0AxMjM0NTY=
jwt.expiration=3600000
